In [63]:
import pandas as pd
import numpy as np

In [3]:
car=pd.read_csv('quikr_car.csv')

In [4]:
car.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [5]:
car.shape # tell about how much data we have like how much rows and columns we have

(892, 6)

In [6]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

## Quality
year has many non-year values,
year object to int,
price has ask for price,
price object to int,
kms driven has kms with integers(should convert like object to integer),
kms driven has nan values,
fuel_type has nan values,
name column has inconsistency so we keep just first 3 words only

In [7]:
car['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [8]:
car['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [9]:
car['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

In [10]:
car['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

# CLEANING OF DATA

In [11]:
backup=car.copy() #used for larger dataset

In [12]:
car['year']

0      2007
1      2006
2      2018
3      2014
4      2014
       ...
887    zest
888    2018
889    2013
890    2014
891    2014
Name: year, Length: 892, dtype: object

In [13]:
car['year'].str.isnumeric() #basically it tells whether the columns has numeric value or not , if it has numeric value then o/p will be True

0       True
1       True
2       True
3       True
4       True
       ...
887    False
888     True
889     True
890     True
891     True
Name: year, Length: 892, dtype: bool

In [14]:
car=car[car['year'].str.isnumeric()] #only that will show which has numeric values

In [15]:
car['year']=pd.to_numeric(car['year'],errors='coerce').fillna(0).astype(int)

In [16]:
car['year']

0      2007
1      2006
2      2018
3      2014
4      2014
       ...
886    2009
888    2018
889    2013
890    2014
891    2014
Name: year, Length: 842, dtype: int64

In [17]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int64
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int64(1), object(5)
memory usage: 46.0+ KB

In [18]:
car=car[car['Price']!="Ask For Price"].copy() # it'll remove the column which has float value

In [19]:
car['Price']=car['Price'].str.replace(',','') #it will remove comma

In [20]:
car['Price']=car['Price'].astype(int)

In [21]:
car['Price']

0       80000
1      425000
3      325000
4      575000
6      175000
        ...
886    300000
888    260000
889    390000
890    180000
891    160000
Name: Price, Length: 819, dtype: int64

In [22]:
car['kms_driven']

0        45,000 kms
1            40 kms
3        28,000 kms
4        36,000 kms
6        41,000 kms
           ...
886    1,32,000 kms
888      27,000 kms
889      40,000 kms
890          Petrol
891          Petrol
Name: kms_driven, Length: 819, dtype: object

In [23]:
car['kms_driven'].str.split(' ')

0        [45,000, kms]
1            [40, kms]
3        [28,000, kms]
4        [36,000, kms]
6        [41,000, kms]
            ...
886    [1,32,000, kms]
888      [27,000, kms]
889      [40,000, kms]
890           [Petrol]
891           [Petrol]
Name: kms_driven, Length: 819, dtype: object

In [24]:
car['kms_driven']=car['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

In [25]:
car['kms_driven']

0       45000
1          40
3       28000
4       36000
6       41000
        ...
886    132000
888     27000
889     40000
890    Petrol
891    Petrol
Name: kms_driven, Length: 819, dtype: object

In [26]:
car['kms_driven']=pd.to_numeric(car['kms_driven'],errors='coerce')

In [27]:
car=car.dropna(subset=['kms_driven'])

In [28]:
car['kms_driven']

0       45000.0
1          40.0
3       28000.0
4       36000.0
6       41000.0
         ...
883     50000.0
885     30000.0
886    132000.0
888     27000.0
889     40000.0
Name: kms_driven, Length: 817, dtype: float64

In [29]:
car.info()

<class 'pandas.core.frame.DataFrame'>
Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int64
 3   Price       817 non-null    int64
 4   kms_driven  817 non-null    float64
 5   fuel_type   816 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 44.7+ KB

In [30]:
car[car['fuel_type'].isna()]

               name company  year   Price  kms_driven fuel_type
132  Toyota Corolla  Toyota  2009  275000     26000.0       NaN

In [31]:
car=car[~car['fuel_type'].isna()]

In [32]:
car['name']

0        Hyundai Santro Xing XO eRLX Euro III
1                     Mahindra Jeep CL550 MDI
3      Hyundai Grand i10 Magna 1.2 Kappa VTVT
4            Ford EcoSport Titanium 1.5L TDCi
6                                   Ford Figo
                        ...
883                Maruti Suzuki Ritz VXI ABS
885                 Tata Indica V2 DLE BS III
886                      Toyota Corolla Altis
888                       Tata Zest XM Diesel
889                        Mahindra Quanto C8
Name: name, Length: 816, dtype: object

In [33]:
car['name'].str.split(' ')

0        [Hyundai, Santro, Xing, XO, eRLX, Euro, III]
1                        [Mahindra, Jeep, CL550, MDI]
3      [Hyundai, Grand, i10, Magna, 1.2, Kappa, VTVT]
4              [Ford, EcoSport, Titanium, 1.5L, TDCi]
6                                        [Ford, Figo]
                            ...
883                  [Maruti, Suzuki, Ritz, VXI, ABS]
885                  [Tata, Indica, V2, DLE, BS, III]
886                          [Toyota, Corolla, Altis]
888                          [Tata, Zest, XM, Diesel]
889                            [Mahindra, Quanto, C8]
Name: name, Length: 816, dtype: object

In [34]:
car['name'].str.split(' ').str.slice(0,3)

0         [Hyundai, Santro, Xing]
1         [Mahindra, Jeep, CL550]
3           [Hyundai, Grand, i10]
4      [Ford, EcoSport, Titanium]
6                    [Ford, Figo]
                  ...
883        [Maruti, Suzuki, Ritz]
885            [Tata, Indica, V2]
886      [Toyota, Corolla, Altis]
888              [Tata, Zest, XM]
889        [Mahindra, Quanto, C8]
Name: name, Length: 816, dtype: object

In [35]:
car['name']=car['name'].str.split(' ').str.slice(0,3).str.join(' ')

In [36]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000     45000.0    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000        40.0    Diesel
3         Hyundai Grand i10   Hyundai  2014  325000     28000.0    Petrol
4    Ford EcoSport Titanium      Ford  2014  575000     36000.0    Diesel
6                 Ford Figo      Ford  2012  175000     41000.0    Diesel
..                      ...       ...   ...     ...         ...       ...
883      Maruti Suzuki Ritz    Maruti  2011  270000     50000.0    Petrol
885          Tata Indica V2      Tata  2009  110000     30000.0    Diesel
886    Toyota Corolla Altis    Toyota  2009  300000    132000.0    Petrol
888            Tata Zest XM      Tata  2018  260000     27000.0    Diesel
889      Mahindra Quanto C8  Mahindra  2013  390000     40000.0    Diesel

[816 rows x 6 columns]

In [37]:
car=car.reset_index(drop=True)

In [38]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000     45000.0    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000        40.0    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000     28000.0    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000     36000.0    Diesel
4                 Ford Figo      Ford  2012  175000     41000.0    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000     50000.0    Petrol
812          Tata Indica V2      Tata  2009  110000     30000.0    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000    132000.0    Petrol
814            Tata Zest XM      Tata  2018  260000     27000.0    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000     40000.0    Diesel

[816 rows x 6 columns]

In [39]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64
 3   Price       816 non-null    int64
 4   kms_driven  816 non-null    float64
 5   fuel_type   816 non-null    object
dtypes: float64(1), int64(2), object(3)
memory usage: 38.4+ KB

In [40]:
car.describe() # it only gives numeric values

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [41]:
car[car['Price']>6e6].reset_index(drop=True) # clearly this is an outlier

                 name   company  year    Price  kms_driven fuel_type
0  Mahindra XUV500 W6  Mahindra  2014  8500003     45000.0    Diesel

In [42]:
car=car[car['Price']<6e6].reset_index(drop=True)

In [43]:
car

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000     45000.0    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000        40.0    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000     28000.0    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000     36000.0    Diesel
4                 Ford Figo      Ford  2012  175000     41000.0    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000     50000.0    Petrol
811          Tata Indica V2      Tata  2009  110000     30000.0    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000    132000.0    Petrol
813            Tata Zest XM      Tata  2018  260000     27000.0    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000     40000.0    Diesel

[815 rows x 6 columns]

In [44]:
car.to_csv('Cleaned Car.csv')

## MODEL

In [74]:
X=car[['name','company','year','kms_driven','fuel_type']]
y=car['Price']

In [75]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

column_trans = ColumnTransformer(
    [('cat', OneHotEncoder(handle_unknown='ignore'), ['name','company','fuel_type'])],
    remainder='passthrough'
)

In [76]:
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression

pipe = make_pipeline(column_trans, LinearRegression())

In [77]:
car=car.dropna().reset_index(drop=True)

In [78]:
#APPLYING TRAIN TEST SPLIT

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [79]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [81]:
model=LinearRegression()

In [82]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [83]:
pipe.predict(pd.DataFrame([[
    'Maruti Suzuki Swift','Maruti',2019,100,'Petrol'
]], columns=['name','company','year','kms_driven','fuel_type']))

array([448176.65290369])

In [84]:
y_pred

array([ 374013.07487077,  621598.71543645,  211122.24696239,
        326551.23447227,  621350.17999726,   79639.67779902,
        318066.44942615,  312324.7655376 ,  554327.21783473,
        350810.520719  ,  313936.09583301,  455691.7684846 ,
        284787.65517979,  405771.33250514,  275653.46437696,
        355826.53464936,   66500.60157459,  259254.06043211,
        -75867.36328163,   60024.85355734,    3125.29593436,
        115196.42060175,  230004.57982811,  612978.52975666,
       1039911.02677462,  171985.82859353,  306091.30612908,
       1606604.65108483,  236548.49084301,  902032.13234096,
        610129.96256549,  144683.21556138,  570870.23032791,
        362711.73329236,  249796.01726259,  233176.22937404,
        480061.80371431,  264948.5313777 ,  839700.27826311,
        370064.69887962,  193186.13233478,  489999.00001062,
        147897.84962974,  193332.35013389,  171943.77994149,
        347494.74449056,  683958.98382682,  226437.22379387,
        645403.82782652,  315000.00011226,   50031.35722799,
        540209.68105101,  506366.95370134,  246287.08601847,
        291139.91155557,  253396.9826146 ,  859241.40534288,
        304359.02746808,  276250.02340119,  578620.5419898 ,
        698999.99988783,  175539.05553449,  614481.12427535,
        839700.27826311,  267402.08779558,  -22464.97260613,
        111931.45454907,  541395.05908155,  501000.0000241 ,
        146482.29897922,   89999.99999317,  314338.41783818,
        259348.65088174,  550272.8031406 ,  334313.88020089,
        829416.7472407 ,  332523.70708229,  307015.62917378,
        297869.01541241,  554301.29861283,  438443.90033112,
        490113.27570257,   46062.09951647, 1487573.21433107,
        584585.39253055,  376747.53601018,  506242.68598174,
        297474.16081091,  338243.82981744, 1891121.35564908,
        238039.48306519,  485279.64638295,  190310.94173638,
        216979.76238429, 1570321.36432036,  382922.99556182,
        429863.06126592,  362927.6142116 ,  242132.4608232 ,
        139415.40344388,  488851.4245481 ,  400745.05152813,
        300225.08368976,  272331.87131218,  513691.90360249,
        182324.649108  ,  415465.73888754,   86886.08127034,
        142446.39660858,   43961.97505525, 1891059.22178928,
        496977.03941485,  143689.07380458,  689998.99994922,
        488560.2397177 ,  102154.3232562 ,  289022.88286058,
       1572920.47026872,  323815.99178459,  117557.50727413,
        737954.20042825,  261869.69887698,  206404.223659  ,
        132491.96475839,  397657.94985097,  442064.40669049,
        586948.11463133,  830725.50151081,  197698.77726003,
        562655.67783723,   49933.30107284,  226437.22379387,
        151190.71874214,  379954.42494038,  301716.29632495,
       1606604.65108483,  374396.36524918,  468522.22687688,
        380960.34233245,  535265.42179983,  615115.93452405,
        597166.58624265,  222198.88125924,   35407.4452536 ,
        644895.37505492,  355826.53464936,  724349.43271665,
        359162.47014964,  250114.53178213,  193040.22321006,
        270453.61966457,   64312.96247596,  362927.6142116 ,
        561994.80466451,   84734.6543026 ,  117557.50727413,
        385473.82472191,  258508.45411452,  228333.93835232,
        539999.99999987,  275578.9037452 ,  364205.2149607 ,
        461008.40190529])

In [85]:
r2_score(y_test,y_pred)

-0.7456266680108647

In [87]:
scores=[]
for i in range(1000):
    X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=i)
    model=LinearRegression()
    pipe.fit(X_train,y_train)
    y_pred=pipe.predict(X_test)
    print(r2_score(y_test,y_pred),i)
    scores.append(r2_score(y_test,y_pred))

0.6590249644441265 0
0.4787115754241703 1
0.6206664532828258 2
0.5610452924871903 3
0.818899890373006 4
0.6634588610159455 5
0.6276335654066811 6
0.629875646968152 7
0.6898275252569628 8
0.570002366980555 9
0.6483945368108857 10
0.6086000495805006 11
0.456991537631223 12
0.6673698969219544 13
0.566708641226517 14
0.710846955454502 15
0.48785265871936456 16
0.6657869234755691 17
0.6089407631572528 18
0.6034073814502598 19
0.6410709224424785 20
0.6210977730177919 21
0.7365807740472743 22
0.6403590588351131 23
0.5492268226839474 24
0.4986544318373979 25
0.6732787159188957 26
0.7035630750518982 27
0.7254727379821893 28
0.6010356941403432 29
0.6245053912002374 30
0.6290243394165796 31
0.7650599065809919 32
0.7854390912879549 33
0.5622351958321786 34
0.683883319381487 35
0.5779283440163461 36
0.6169326155180646 37
0.5393853548815948 38
0.7164028704218754 39
0.31892617981191784 40
0.6733628044219369 41
0.5731677624518181 42
0.6791726528771573 43
0.6604144860132009 44
0.6975409771842054 45
0.5258705780713024 46
0.5882131243618636 47
0.7540170677087443 48
0.6861721720792784 49
0.503806604496589 50
0.5901779448654767 51
0.6325679093960973 52
0.6637852931671141 53
0.5867400099987241 54
0.6974929128180667 55
0.7171749052615716 56
0.7195101295535161 57
0.7607592075482661 58
0.48428064066481735 59
0.5849349161291171 60
0.5244371263215981 61
0.43303202220262027 62
0.6189632379886317 63
0.6075690619600851 64
0.6349251096364323 65
0.4810243163227941 66
0.6590615193364594 67
0.621458600527236 68
0.735449991178353 69
0.6997085066962483 70
0.7185579614349371 71
0.5796155894082362 72
0.6844288087983825 73
0.5518285477223792 74
0.5835223531010414 75
0.4492930527941412 76
0.6053404245274558 77
0.5738463650009513 78
0.646061777816183 79
0.5893906646136042 80
0.6086470114788426 81
0.6767911542205569 82
0.7388100889162368 83
0.6389714804272421 84
0.6358492376830169 85
0.6852033440876324 86
0.5372926139759246 87
0.6029854826795464 88
0.638408266379242 89
0.6809830031468029 90
0.5868171954561971 91
0.6883077381360168 92
0.49450090331276886 93
0.6331518595835605 94
0.6589603528925312 95
0.6381943826898396 96
0.6856716765677253 97
0.6751758397387301 98
0.5992324698399507 99
0.6899601503208468 100
0.6600098626090505 101
0.6837468638264657 102
0.5929631486055642 103
0.7041451316306615 104
0.5649589968981553 105
0.607837345545813 106
0.5763647173014819 107
0.5851016535510195 108
0.7107005842129133 109
0.6766879992930406 110
0.6559246479060932 111
0.5127811879231217 112
0.6955986500707971 113
0.7126106043267523 114
0.5634755890266703 115
0.590251442386696 116
0.6525738888266408 117
0.5259726192642511 118
0.7228177207919579 119
0.6582289744877718 120
0.5953149175833267 121
0.7076144375472843 122
0.6261016575324201 123
0.8216321065785199 124
0.6810048858264355 125
0.6377697736526521 126
0.623946068408415 127
0.5857326007282825 128
0.5503692310333089 129
0.6062858366226994 130
0.5323289208701318 131
0.6578401703031713 132
0.5821582248317521 133
0.7633579596586116 134
0.7148756736406826 135
0.5440208543231129 136
0.7129203150854249 137
0.6644024551994236 138
0.559097073937015 139
0.7181358892248135 140
0.5866995398658392 141
0.6612224478292044 142
0.7117858799298519 143
0.6300994573857568 144
0.5545537339468097 145
0.635956620090999 146
0.5880533036296465 147
0.5634845909453506 148
0.6353581916884796 149
0.6277566910388019 150
0.7724665974424728 151
0.5656591429767597 152
0.5011968195590146 153
0.6341781787616323 154
0.65885932895691 155
0.42238457854282474 156
0.7312038233143863 157
0.629845493801676 158
0.6780738639786501 159
0.6478220066033424 160
0.5930929896248194 161
0.6642598983795924 162
0.5706479505342106 163
0.5888067663888386 164
0.6902584563361209 165
0.6571449502430304 166
0.4980002789617928 167
0.5687877085207518 168
0.6962792024040558 169
0.6922986129994213 170
0.6497193326202073 171
0.8164620753900941 172
0.7188901377891791 173
0.5470825491452251 174
0.614316489302577 175
0.6725499995942079 176
0.6500728487180139 177
0.7143472112376505 178
0.6795681301454244 179
0.6414506950481849 180
0.61699325201314 181
0.674483910245113 182
0.6645425066504521 183
0.5049705966982594 184
0.6668447269039253 185
0.7358344483980158 186
0.6454049153891022 187
0.6955475897364984 188
0.5728658341068491 189
0.7042506505399689 190
0.6625268231799448 191
0.5791387199286979 192
0.6910797123615111 193
0.7382174554311971 194
0.6272253828043912 195
0.6318292942334702 196
0.7493883167748441 197
0.4022801832112458 198
0.7100630189102946 199
0.7155301365936191 200
0.4522114137584645 201
0.6011616452682628 202
0.7847693437666802 203
0.5827679308966948 204
0.6723603829380628 205
0.7711416958532176 206
0.5696108686247106 207
0.6766954721548852 208
0.26906514185647346 209
0.49255288377203754 210
0.5097745075552962 211
0.5691027327451267 212
0.6186039618759585 213
0.675913880897423 214
0.6179089721085356 215
0.5303632563728018 216
0.636714453268359 217
0.5417923705224519 218
0.5692911592150599 219
0.5905377609658085 220
0.6818021563301084 221
0.4755035036660644 222
0.4958221018340785 223
0.5517694380666264 224
0.7244799554681969 225
0.7406285127534518 226
0.6427874905912072 227
0.7309038198711625 228
0.5826960861656343 229
0.555145082106647 230
0.5864571930652002 231
0.6307956250735146 232
0.44062373866270255 233
0.7245030153208705 234
0.5867036047267102 235
0.7010069556821927 236
0.6090800938772304 237
0.5266450095589915 238
0.5939785995453967 239
0.5705683557413048 240
0.4845444837402809 241
0.5173019674600434 242
0.6399596791612494 243
0.4958526481050892 244
0.7214279924896108 245
0.7796501601441338 246
0.746306205456921 247
0.7800346598989377 248
0.5432324373120493 249
0.6071006632479348 250
0.5083574104039892 251
0.5594154074140326 252
0.6509886890512551 253
0.5879517116508156 254
0.7699444047132784 255
0.5427038940676572 256
0.6989240886420283 257
0.6602038308688989 258
0.5644983703055957 259
0.715414421536327 260
0.7568760438115103 261
0.7048029819445207 262
0.7236940710774528 263
0.6347587716019305 264
0.6262729320535048 265
0.6586435919633649 266
0.653008407699079 267
0.4747659529782152 268
0.5487567842837141 269
0.6272567010633509 270
0.5493924058528266 271
0.6220709119371806 272
0.6177339739351044 273
0.7171943134854456 274
0.6261410148912161 275
0.753434192555578 276
0.6970064095340094 277
0.6287058778346712 278
0.7884242231283631 279
0.6615555260470527 280
0.654466717074629 281
0.6889228699750403 282
0.7344518987429718 283
0.7173676059661597 284
0.5664029017058523 285
0.7224375373800136 286
0.5928209253885887 287
0.48049589007584115 288
0.45184305734751906 289
0.5200208150564232 290
0.6947842498481136 291
0.5407035116003984 292
0.7510598056991731 293
0.8132643990648044 294
0.63098310750597 295
0.7431848888988377 296
0.7010417518661771 297
0.5330360701330568 298
0.6736008645824973 299
0.7690364640097438 300
0.6807266607458904 301
0.7634547969076053 302
0.48723695671830125 303
0.6515741305852774 304
0.5896464022678353 305
0.7951831342393267 306
0.6918171222061769 307
0.6490608589746325 308
0.7399717950742827 309
0.6748780816094466 310
0.6069463984510589 311
0.5082874695341661 312
0.4995117614363147 313
0.5452649511188563 314
0.7375174288553235 315
0.583094640068317 316
0.6615210824379318 317
0.6538615316698344 318
0.5117568157458228 319
0.47565888274612755 320
0.5930869247584541 321
0.5331015528218226 322
0.569854819267255 323
0.6196789152735728 324
0.5365142614362737 325
0.5929197865287636 326
0.7232983227547041 327
0.6936896506042827 328
0.514394185229615 329
0.6551586220967761 330
0.5063683589440191 331
0.6012789618005813 332
0.5731418740216545 333
0.6980506475689447 334
0.6015846901487618 335
0.509669848990133 336
0.6707616750618582 337
0.6187269329740095 338
0.5682106534095812 339
0.7122703980784642 340
0.7319022976570478 341
0.6000171713762148 342
0.6714107988365936 343
0.691432517022707 344
0.6448772556721809 345
0.6674235090526452 346
0.589476854481735 347
0.6989981919941813 348
0.6226018437873541 349
0.766284901352875 350
0.7074403649792036 351
0.5742354430623924 352
0.4602570375975854 353
0.7286092047719245 354
0.6677402087143585 355
0.6985200143657131 356
0.6514058354419792 357
0.7076068299044116 358
0.583333523051291 359
0.7067961507402578 360
0.6772115624349438 361
0.5385689925477221 362
0.6953308300442493 363
0.7148882831376941 364
0.5633691109184071 365
0.6770615476192561 366
0.465201331002848 367
0.7446908225132481 368
0.7339218498282771 369
0.6969956381550212 370
0.6248952811361754 371
0.6434096632064272 372
0.669562513493821 373
0.5158133858597123 374
0.5758224447815419 375
0.6845719343984469 376
0.5384975402649688 377
0.7351593133026333 378
0.7702058071478656 379
0.6141675656621953 380
0.698667651567336 381
0.7054243649682043 382
0.8071047731609815 383
0.713201831529164 384
0.70470537997845 385
0.6861820954300146 386
0.5959186537270573 387
0.5647612531232794 388
0.43368279838610213 389
0.7343579269826107 390
0.5622033358866729 391
0.8082355182535774 392
0.3785106559610302 393
0.6367658604754189 394
0.7214809684511981 395
0.5506462957183078 396
0.5941435986249078 397
0.7003253013469457 398
0.7191554245659828 399
0.6361155169248465 400
0.5658894132300856 401
0.5588781326926877 402
0.4976676975109474 403
0.6154363045488789 404
0.6494268450331373 405
0.574563271263906 406
0.6632642384701408 407
0.67962751354984 408
0.6685614473400601 409
0.6860656772775416 410
0.6551660150477218 411
0.6565966494037926 412
0.5172674088861855 413
0.5840077633847025 414
0.5402034524219245 415
0.4703561489248276 416
0.6928245550683381 417
0.6768311896789452 418
0.6702122161937591 419
0.7205702007285024 420
0.6700295461076565 421
0.6886343133383055 422
0.6500526575475827 423
0.6328001639252425 424
0.579369182577129 425
0.4345025691398525 426
0.7074385997798579 427
0.5300753111123061 428
0.6586028068473198 429
0.6816045947037345 430
0.7746849235174109 431
0.648608051805204 432
0.845696581888373 433
0.6072448390304722 434
0.7763096122896203 435
0.5834521495553009 436
0.7060761214397046 437
0.6467902851061639 438
0.7164553064261723 439
0.6412338433606264 440
0.6707811462698836 441
0.6096059403387823 442
0.8021933985485086 443
0.7720389393563466 444
0.7427390999133492 445
0.7215037223640222 446
0.6240906780345152 447
0.5661467722654654 448
0.7530798504942641 449
0.7764757043929493 450
0.5497230190889115 451
0.5774704947858302 452
0.6333018107717374 453
0.6490882306070378 454
0.6403711001854135 455
0.49814428106149455 456
0.513315773821317 457
0.7295305246948557 458
0.6464311163689762 459
0.7460777945004005 460
0.5490086784059703 461
0.5891696394355362 462
0.7756029561556324 463
0.5044134856382775 464
0.6222175682235884 465
0.6795316117444941 466
0.5990083770730552 467
0.6823555166913259 468
0.6499325347535082 469
0.4905755060165875 470
0.5427569437727165 471
0.3508155103596945 472
0.7210218928587904 473
0.7031291308351975 474
0.7744444250343424 475
0.618537345227318 476
0.6266888090157439 477
0.7329133176777904 478
0.5341695867278988 479
0.5772399398200042 480
0.6002671638161212 481
0.6093125045500674 482
0.5348486579084106 483
0.5553223595913152 484
0.5177873842569483 485
0.6340213044518059 486
0.5806115949724375 487
0.7406257105552017 488
0.6327611336310076 489
0.5237174566636318 490
0.7762557067990835 491
0.6033137168782036 492
0.6135790896933966 493
0.6711004517382296 494
0.586685256182492 495
0.7010663764477365 496
0.6498371658008731 497
0.6625445943215136 498
0.7795265737082879 499
0.6827008230700484 500
0.5996108619856958 501
0.5604783150115992 502
0.6311880707776663 503
0.4980153584971446 504
0.6694507473911635 505
0.6669595227239373 506
0.7637535561901339 507
0.6871954933601259 508
0.6534925354557997 509
0.625271675156112 510
0.6219226016551416 511
0.6376744997373012 512
0.7256286129358573 513
0.660377477155748 514
0.7836013123541877 515
0.7193516625573886 516
0.7590948022723605 517
0.5945451415183329 518
0.6750624312740332 519
0.6941296770892743 520
0.683178212600903 521
0.497975440544176 522
0.5697533313775547 523
0.5324635944152627 524
0.4837859535027411 525
0.6351540027094323 526
0.6891793959355492 527
0.7635499724147391 528
0.653606041463609 529
0.627730016888473 530
0.6291923854739114 531
0.6366682114592241 532
0.7376195584013161 533
0.5087371200955235 534
0.5794192933590095 535
0.6378133019834273 536
0.5176206643228044 537
0.7050042242010948 538
0.5758242851841444 539
0.6923443085221587 540
0.6007479489694912 541
0.6790218946955018 542
0.5427726267149051 543
0.6958979121343046 544
0.46337209738523977 545
0.7139048786583668 546
0.3235567716984602 547
0.7312973718385913 548
0.5020386693087138 549
0.6214109815811106 550
0.6739208351153958 551
0.5334869444899256 552
0.7244967355070167 553
0.6239324976351612 554
0.7146911595080214 555
0.5554045953666984 556
0.5144416545601562 557
0.69554635765174 558
0.7086564677692642 559
0.6141846141941623 560
0.49490183649729247 561
0.7054035567364823 562
0.589413957791553 563
0.6576388701010141 564
0.674527671067185 565
0.7696950687374907 566
0.6601638262466902 567
0.7187213346724481 568
0.6175930422224887 569
0.6403612739691391 570
0.6471810444468338 571
0.6854421239989463 572
0.6243539334501895 573
0.574587253442046 574
0.6950666181400308 575
0.678637343381206 576
0.7611186857832725 577
0.6666162420028325 578
0.6317937644223552 579
0.5933721770825631 580
0.6461128617688012 581
0.49721635542967857 582
0.5837304290803977 583
0.5219282161399612 584
0.5789380503591438 585
0.6937896396839353 586
0.63941506314775 587
0.7001439339024728 588
0.6931741554652189 589
0.5897255813554203 590
0.6972023477832652 591
0.7234150937980323 592
0.7177844949537864 593
0.5953324308704849 594
0.3874066178995952 595
0.5581904150395991 596
0.5619731163699367 597
0.5643344124580693 598
0.5258325390551423 599
0.5153855255575243 600
0.5706095247563945 601
0.711155535653095 602
0.5858397922586338 603
0.5788208902791021 604
0.7394483351927468 605
0.4860745564186395 606
0.6077823989470548 607
0.6830854417918296 608
0.6080597739083344 609
0.47375729777572795 610
0.6037250303031283 611
0.6044012340803959 612
0.6049837679796393 613
0.6679021729938464 614
0.5918473897299541 615
0.37129479185751113 616
0.5820774317344917 617
0.6802629530735589 618
0.606958820132949 619
0.4976529533577083 620
0.7211843660930584 621
0.6028388254689336 622
0.5126384819035807 623
0.7605189458469304 624
0.5958506624280202 625
0.6934838924147517 626
0.5130310749626403 627
0.6716333824058289 628
0.6444001329812461 629
0.5865132841778744 630
0.6951454622054817 631
0.6893511443108477 632
0.6432875417991938 633
0.5160308781344325 634
0.5964425195496194 635
0.6789548681924149 636
0.6658551901052419 637
0.7385857448556322 638
0.5432006687671849 639
0.5651072390919922 640
0.6711174488002671 641
0.6803996353201682 642
0.6024180466331811 643
0.4849506690729041 644
0.6955633727457575 645
0.5974212396131237 646
0.4811514639399015 647
0.6039911935562419 648
0.6484869672965536 649
0.6751846020245487 650
0.6153003923718802 651
0.7503716391212495 652
0.7691284234719353 653
0.6502218894542409 654
0.6499170748740619 655
0.5853857442977897 656
0.46068699541538705 657
0.6752814612616577 658
0.6821513200250469 659
0.7256204224728999 660
0.7687202540241269 661
0.5483458454295649 662
0.5153435818255048 663
0.47986873358765847 664
0.6709602994903542 665
0.6207978149994371 666
0.698954091219324 667
0.716067480446208 668
0.7371097061125309 669
0.7503923625335814 670
0.5259808993191707 671
0.6650588972060862 672
0.7328884035491199 673
0.664648161930961 674
0.6285925098445151 675
0.6620510810151414 676
0.5532213452692387 677
0.7558863566912934 678
0.6584816087617843 679
0.6211612492250125 680
0.5400911767131444 681
0.7208059281909363 682
0.698569274883323 683
0.5896605092067879 684
0.6219826295319083 685
0.8314290253170018 686
0.633203460736159 687
0.5383258325778739 688
0.7932082109955947 689
0.6068446430555848 690
0.6814867384059959 691
0.6493548528081434 692
0.6541370242726536 693
0.6907491342796935 694
0.7115345104101543 695
0.6608422541826111 696
0.5533664152890683 697
0.7516676269452 698
0.6662991567629664 699
0.47695879107554284 700
0.7039705088957835 701
0.5463440260146257 702
0.7293942650662313 703
0.5353056758073138 704
0.6827144313101858 705
0.7209972462207797 706
0.6604087610199305 707
0.6549814361322654 708
0.5333090220050671 709
0.6449084284844226 710
0.6988069555141454 711
0.8112927234763894 712
0.8016624551948415 713
0.6569191762458201 714
0.677855540156955 715
0.7205305746666084 716
0.7319387989341803 717
0.3422373588402795 718
0.6458788584692694 719
0.5559913638095193 720
0.5874019923238161 721
0.6768858731725409 722
0.6850187786810613 723
0.6417853210988893 724
0.6219789465941208 725
0.6519779181489489 726
0.6891870527845798 727
0.6140499004203541 728
0.580025706464642 729
0.748033629544703 730
0.5285986454652442 731
0.7939556716538534 732
0.6720203787153662 733
0.5889184155337153 734
0.5397421731052098 735
0.612971296450797 736
0.5038430895040857 737
0.7120261466737521 738
0.5987712986580633 739
0.6287789867253027 740
0.593690210529698 741
0.7512196274295415 742
0.73179085583128 743
0.5720561990233546 744
0.6130931374626479 745
0.6632488258020862 746
0.553025062814178 747
0.5926586653428932 748
0.5104273598526694 749
0.542174210162822 750
0.7059011137171265 751
0.7641667697256226 752
0.6888756865690308 753
0.7143038711015546 754
0.6392215105817971 755
0.6011621936437733 756
0.7817591040376604 757
0.6169879604952948 758
0.6331851185381487 759
0.6523205372928284 760
0.6657862152844071 761
0.7083866054609655 762
0.6417682689362887 763
0.6178731669128171 764
0.6603919430635844 765
0.6258489312535997 766
0.6269065134785872 767
0.5344149317621442 768
0.757842193265803 769
0.6719419592248639 770
0.6976764767275508 771
0.7075424583233643 772
0.6080240780018291 773
0.557680456524971 774
0.5850865297525771 775
0.5554990825136905 776
0.3625925172710103 777
0.7045211002551048 778
0.6736260776899711 779
0.6545896851685602 780
0.8251456386465388 781
0.7086607436480012 782
0.7833624173641569 783
0.6410172298009397 784
0.6341838667981202 785
0.63752912750104 786
0.6625464235909448 787
0.7001446358113934 788
0.42350387798707734 789
0.7190150664637349 790
0.7028108225986164 791
0.7349877427442817 792
0.738332765001398 793
0.6578212326755868 794
0.5603504000567727 795
0.7151131584443126 796
0.6066226021532087 797
0.6345178807929495 798
0.7459400542184745 799
0.6406351534072652 800
0.507247333648503 801
0.6130902182312066 802
0.653310464743198 803
0.5499468832725154 804
0.597722303404637 805
0.6454587190318457 806
0.7460076382834178 807
0.3888195241904723 808
0.5655208445511521 809
0.5549608532680702 810
0.6486047242039936 811
0.6613210807714464 812
0.5258502189813195 813
0.7881348252939185 814
0.6278195632726349 815
0.6022786890922363 816
0.7028447527946028 817
0.6569188037385527 818
0.6639768653659338 819
0.5586351328869423 820
0.7773541387955922 821
0.6852141702358268 822
0.5951115977111737 823
0.44789727701236104 824
0.7238874994317586 825
0.6643153816869023 826
0.76012444039428 827
0.653842693057991 828
0.6380225260383316 829
0.48403225803866734 830
0.7088488403797008 831
0.7752283888254091 832
0.5827484155766139 833
0.7430164632343845 834
0.6403092220707169 835
0.5720659656150222 836
0.6388386879598348 837
0.6564950842966354 838
0.5945763589500013 839
0.7293165246749667 840
0.7584416567478761 841
0.7251575848817073 842
0.7081148934903279 843
0.6551128553213198 844
0.4946244876244571 845
0.6089793925882376 846
0.6132967600408321 847
0.5751212907600101 848
0.6888677620151324 849
0.7279019577935034 850
0.6005448720960992 851
0.6351597923243689 852
0.6222191738370829 853
0.5506788460425853 854
0.605469308206267 855
0.5420878878942155 856
0.502352553564634 857
0.7453818740093481 858
0.5257426959279602 859
0.7757717253472769 860
0.5784662993586187 861
0.6714756825206539 862
0.5781232734243884 863
0.6638870194281612 864
0.5497626112790176 865
0.6200419811605403 866
0.6024017158114121 867
0.5677088345968548 868
0.6331686156936966 869
0.5748649223444295 870
0.46720103589971995 871
0.6581982872898292 872
0.6209505796618396 873
0.686547574499203 874
0.6563796520898277 875
0.648074916045769 876

In [88]:
np.argmax(scores)

np.int64(433)

In [89]:
scores[np.argmax(scores)]

0.845696581888373

In [90]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=np.argmax(scores))
model=LinearRegression()
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
r2_score(y_test,y_pred)

0.845696581888373

In [91]:
import pickle

In [92]:
pickle.dump(model,open('LinearRegressionModel.pkl','wb'))

In [94]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift','Maruti',2019,100,'Petrol']],columns=['name','company','year','kms_driven','fuel_type']))

array([458931.57216377])